### ISSUE TITLE
User avariable amount

### ISSUE THREAD

**Issue by Alessandro-Boseggia** [SendGram/SendgramBank#17]
# ToDo
- [x] Add amount in model
- [x] create GET /user/amount endpoint to retrieve available amount for the user (restricted endpoint)
- [x] Alter amount on new transaction
